apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"external-secrets.io/v1beta1","kind":"SecretStore","metadata":{"annotations":{},"name":"thanos-secret-store","namespace":"open-cluster-management-observability"},"spec":{"provider":{"aws":{"auth":{"jwt":{"serviceAccountRef":{"name":"externalsecret-operator-config-external-secrets"}}},"region":"us-east-1","service":"SecretsManager"}}}}
  name: thanos-secret-store
  namespace: open-cluster-management-observability  ##NAMESPACE $USER_NAMESPACE (The namespace where the OCP secret is going to be created in)
spec:
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: externalsecret-operator-config-external-secrets   ##The Service Account $SA_NAME that is going to have access to the ocp secret)
            namespace: open-cluster-management-observability 
      region: us-east-1
      service: SecretsManager
